import { Color, Graphics, Label, LabelOutline, Node, UITransform } from 'cc';
import { LayoutPeg, LevelLayout, PegType, saveCustomLayout } from './LevelLayout';

const TYPES: { type: PegType; name: string; color: Color }[] = [
  { type:'normal', name:'普通', color:new Color(76,188,105) }, { type:'gold', name:'黄金', color:new Color(245,190,52) },
  { type:'reset', name:'重置', color:new Color(182,92,222) }, { type:'bomb', name:'爆炸', color:new Color(240,105,52) },
  { type:'spring', name:'弹簧', color:new Color(255,115,181) }, { type:'split', name:'分裂', color:new Color(93,168,244) },
  { type:'coin', name:'牛币', color:new Color(238,167,42) }, { type:'prism', name:'棱镜', color:new Color(137,103,231) },
];

/** Built-in, touch-first layout editor. It stores normalized peg positions and needs no backend. */
export class LevelEditorLayer {
  readonly node = new Node('LevelEditorLayer');
  private shade!: Graphics; private panel!: Graphics; private title!: Label; private info!: Label; private palette: Node[]=[];
  private width=0; private height=0; private board={left:0,right:0,bottom:0,top:0}; private type:PegType='normal'; private pegs:LayoutPeg[]=[];
  constructor(parent:Node, private readonly onApply:(layout:LevelLayout)=>void){this.node.parent=parent;this.shade=this.node.addComponent(Graphics);const panelNode=new Node('EditorPanel');panelNode.parent=this.node;panelNode.addComponent(UITransform);this.panel=panelNode.addComponent(Graphics);this.title=this.label('EditorTitle',34,new Color(255,247,214));this.title.node.parent=panelNode;this.title.string='牧场布局编辑器';this.info=this.label('EditorInfo',18,new Color(255,247,214));this.info.node.parent=panelNode;this.makePalette(panelNode);this.node.active=false;}
  get visible(){return this.node.active;} show(layout?:LevelLayout){this.pegs=layout?[...layout.pegs]:[];this.node.active=true;this.refresh();} hide(){this.node.active=false;}
  resize(width:number,height:number){this.width=width;this.height=height;this.node.setPosition(0,0);this.node.getComponent(UITransform)?.setContentSize(width,height);this.shade.clear();this.shade.fillColor=new Color(12,27,40,220);this.shade.rect(0,0,width,height);this.shade.fill();const panel=this.node.children[0];panel.setPosition(width/2,height/2);panel.getComponent(UITransform)!.setContentSize(Math.min(width*.92,650),Math.min(height*.92,1050));const w=panel.getComponent(UITransform)!.contentSize.width,h=panel.getComponent(UITransform)!.contentSize.height;this.panel.clear();this.panel.fillColor=new Color(82,55,37);this.panel.roundRect(-w/2,-h/2,w,h,28);this.panel.fill();this.panel.fillColor=new Color(255,239,192);this.panel.roundRect(-w/2+7,-h/2+7,w-14,h-14,22);this.panel.fill();this.title.node.setPosition(0,h*.43);this.info.node.setPosition(0,h*.385);this.board={left:-w*.43,right:w*.43,bottom:-h*.27,top:h*.31};this.palette.forEach((node,index)=>node.setPosition(-w*.36+(index%4)*w*.24,-h*.39-Math.floor(index/4)*54));this.refresh();}
  handleTap(x:number,y:number){const panel=this.node.children[0];const localX=x-panel.position.x,localY=y-panel.position.y;const w=panel.getComponent(UITransform)!.contentSize.width,h=panel.getComponent(UITransform)!.contentSize.height;if(localY<-h*.45){this.saveAndApply();return true;}for(let i=0;i<TYPES.length;i++){const px=-w*.36+(i%4)*w*.24,py=-h*.39-Math.floor(i/4)*54;if(Math.abs(localX-px)<w*.10&&Math.abs(localY-py)<24){this.type=TYPES[i].type;this.refresh();return true;}}if(localX>=this.board.left&&localX<=this.board.right&&localY>=this.board.bottom&&localY<=this.board.top){const nx=(localX-this.board.left)/(this.board.right-this.board.left),ny=(localY-this.board.bottom)/(this.board.top-this.board.bottom);const nearby=this.pegs.findIndex((peg)=>Math.hypot(peg.x-nx,peg.y-ny)<.035);if(nearby>=0)this.pegs.splice(nearby,1);else this.pegs.push({x:nx,y:ny,type:this.type});this.refresh();}return true;}
  private saveAndApply(){const layout:LevelLayout={id:'my-ranch',target:Math.max(80,this.pegs.length*5),pegs:this.pegs};saveCustomLayout(layout);this.onApply(layout);this.hide();}
  private makePalette(parent:Node){TYPES.forEach((item)=>{const node=new Node(item.type);node.parent=parent;node.addComponent(UITransform).setContentSize(120,42);const g=node.addComponent(Graphics);g.fillColor=item.color;g.roundRect(-58,-18,116,36,17);g.fill();const label=this.label(item.name,16,new Color(255,255,255));label.node.parent=node;label.string=item.name;});}
  private refresh(){if(!this.node.active||!this.width)return;const panel=this.node.children[0];const g=panel.getComponent(Graphics)!;const w=panel.getComponent(UITransform)!.contentSize.width,h=panel.getComponent(UITransform)!.contentSize.height;g.clear();g.fillColor=new Color(82,55,37);g.roundRect(-w/2,-h/2,w,h,28);g.fill();g.fillColor=new Color(255,239,192);g.roundRect(-w/2+7,-h/2+7,w-14,h-14,22);g.fill();g.fillColor=new Color(167,216,129);g.roundRect(this.board.left,this.board.bottom,this.board.right-this.board.left,this.board.top-this.board.bottom,18);g.fill();this.pegs.forEach((peg)=>{const c=TYPES.find((item)=>item.type===peg.type)!.color;g.fillColor=c;g.circle(this.board.left+peg.x*(this.board.right-this.board.left),this.board.bottom+peg.y*(this.board.top-this.board.bottom),13);g.fill();});g.fillColor=new Color(95,178,89);g.roundRect(-w*.31,-h*.485,w*.62,42,20);g.fill();this.info.string=`已放置 ${this.pegs.length} 个钉子 · 当前：${TYPES.find((item)=>item.type===this.type)!.name} · 点击已有钉子可删除`;}
  private label(name:string,size:number,color:Color){const node=new Node(name);node.addComponent(UITransform).setContentSize(680,54);const label=node.addComponent(Label);label.fontSize=size;label.lineHeight=size+6;label.color=color;label.horizontalAlign=Label.HorizontalAlign.CENTER;label.verticalAlign=Label.VerticalAlign.CENTER;const outline=node.addComponent(LabelOutline);outline.width=Math.max(2,Math.round(size*.08));outline.color=new Color(73,47,29,210);return label;}
}
